#!/usr/bin/env python3
"""
guardrail.py — Enforce lessons as CODE before every task.

Run this BEFORE starting a task of a given type. It loads the guardrail rules
generated by upgrade.py (guardrails/<type>.py) and executes them. A rule that
returns ok=False BLOCKS the task with exit 2 — the lesson is enforced by
execution, not by the model reading a doc.

Usage:
    python3 guardrail.py <task_type> "<task description>"
    python3 guardrail.py ppt "做一个 20 页产品介绍 PPT"

Exit codes:
    0  all rules passed (or no rules for this type)
    2  a rule blocked the task — fix the flagged issue first

Env vars:
    HERMES_HOME    path to Hermes home (default: ~/.hermes)
"""

import sys
import os
import importlib.util
from pathlib import Path

GUARDRAILS_DIR = None
if os.environ.get("HERMES_HOME"):
    GUARDRAILS_DIR = Path(os.environ["HERMES_HOME"]) / "guardrails"
elif not GUARDRAILS_DIR:
    # fallback: repo layout (<repo>/guardrails when run from scripts/)
    cand = Path(__file__).parent.parent / "guardrails"
    if cand.exists():
        GUARDRAILS_DIR = cand
if not GUARDRAILS_DIR:
    GUARDRAILS_DIR = Path.home() / ".hermes" / "guardrails"

TASK_TYPES = ["ppt", "pdf", "research", "code", "image", "data", "chat", "general"]


def load_module(typ: str):
    path = GUARDRAILS_DIR / f"{typ}.py"
    if not path.exists():
        return None
    spec = importlib.util.spec_from_file_location(f"guardrails_{typ}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    typ = sys.argv[1].lower()
    task = sys.argv[2]
    if typ not in TASK_TYPES:
        print(f"Unknown task type '{typ}'. Use one of: {', '.join(TASK_TYPES)}")
        sys.exit(1)

    mod = load_module(typ)
    if mod is None:
        print(f"✓ No guardrail rules for '{typ}' — nothing to enforce.")
        sys.exit(0)

    # Print lessons as a structured checklist — the agent must address these
    rules = getattr(mod, "RULES", [])
    if rules:
        print(f"📋 {len(rules)} lesson(s) to respect for '{typ}' tasks:")
        for r in rules:
            print(f"   - {r.get('date','')}: {r.get('lesson','')}")

    blocked = 0
    for name in dir(mod):
        if not name.startswith("check_"):
            continue
        fn = getattr(mod, name)
        try:
            ok, msg = fn(task)
        except Exception as e:
            ok, msg = False, f"guardrail error: {e}"
        if not ok:
            blocked += 1
            print(f"✗ BLOCKED by {name}: {msg}")
        else:
            print(f"✓ {name}: passed")

    if blocked:
        print(f"\n❌ {blocked} rule(s) blocked this task. Fix first, then retry.")
        sys.exit(2)
    print("\n✅ All guardrails passed. Proceed.")


if __name__ == "__main__":
    main()
