#!/usr/bin/env python3
"""
upgrade.py — Turn lessons into executable guardrail code.

This is the core of the "code over docs" philosophy: a lesson is NOT appended
to a markdown skill file (docs rely on the model reading them). Instead it is
compiled into a runnable rule in guardrails/<type>.py, which the guardrail.py
checker enforces BEFORE the task runs. Rules are code: they execute, or they
block.

Usage:
    python3 upgrade.py            # dry-run: show rules that would be (re)generated
    python3 upgrade.py --apply    # actually write guardrail code

Env vars:
    HERMES_HOME    path to Hermes home (default: ~/.hermes)
"""

import os
import re
import sys
import json
from pathlib import Path

HERMES_HOME = Path(os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes")))
LESSONS_DIR = HERMES_HOME / "skills" / "lessons"
GUARDRAILS_DIR = HERMES_HOME / "guardrails"
RULES_INDEX = GUARDRAILS_DIR / "_index.json"

# Task types are generic words (NOT project-specific skill names) — any agent
# can classify a task into one of these buckets.
TASK_TYPES = ["ppt", "pdf", "research", "code", "image", "data", "chat", "general"]


def parse_lessons():
    items = []
    if not LESSONS_DIR.is_dir():
        return items
    seen = set()
    for fn in sorted(os.listdir(LESSONS_DIR)):
        if not fn.endswith(".md"):
            continue
        typ = fn[:-3]
        if typ not in TASK_TYPES:
            typ = "general"
        content = (LESSONS_DIR / fn).read_text(encoding="utf-8", errors="ignore")
        blocks = re.split(r"^##\s+", content, flags=re.M)
        for b in blocks[1:]:
            date_m = re.match(r"(\d{4}-\d{2}-\d{2})[^\n]*", b)
            lesson_m = re.search(r"\*\*教训\*\*[:：]\s*(.+?)(?:\n\n|\Z)", b, re.S)
            if date_m and lesson_m:
                key = (typ, date_m.group(1))
                if key in seen:
                    continue
                seen.add(key)
                # 结构化约束：**约束**：must_contain = 词1, 词2 / must_not = 词1
                cons = {"must_contain": [], "must_not": []}
                con_m = re.search(r"\*\*约束\*\*[:：](.+)", b, re.S)
                if con_m:
                    for kind, pat in [("must_contain", r"must_contain\s*=\s*([^\n]+)"), ("must_not", r"must_not\s*=\s*([^\n]+)")]:
                        m = re.search(pat, con_m.group(1))
                        if m:
                            cons[kind] = [w.strip() for w in m.group(1).split(",") if w.strip()]
                items.append({
                    "type": typ,
                    "date": date_m.group(1),
                    "lesson": lesson_m.group(1).strip()[:300],
                    "must_contain": cons["must_contain"],
                    "must_not": cons["must_not"],
                })
    return items


def lesson_to_rule(lesson):
    """Compile a lesson into a RULES data entry (checks are built separately)."""
    lit = json.dumps(lesson["lesson"], ensure_ascii=False)
    return f'''
# Lesson {lesson['date']}: {lesson['lesson'][:60]}
    {{"date": "{lesson['date']}", "lesson": {lit},
     "must_contain": {json.dumps(lesson['must_contain'], ensure_ascii=False)},
     "must_not": {json.dumps(lesson['must_not'], ensure_ascii=False)}}},
'''

def rules_module(typ, lessons):
    """Generate guardrails/<type>.py with RULES data + real enforcement checks.

    Each lesson's structured constraints (must_contain/must_not) compile into a
    check function that BLOCKS violations (exit 2). Works out of the box —
    no custom code needed. Lessons without constraints still get the generic
    completeness check.
    """
    rules_lines = "\n".join(lesson_to_rule(l) for l in lessons)
    checks = "\n".join(l_check_code(typ, l) for l in lessons)
    return f'''# Auto-generated guardrail rules for task type "{typ}".
# Generated by upgrade.py from lessons/ — do not edit by hand; re-run upgrade.py.
# These rules are CODE: they run before the task and can block it (exit 2).

RULES = [
{rules_lines}]

{checks}
def check_{typ}(task_desc: str) -> tuple[bool, str]:
    """Generic completeness check — works out of the box, no config needed."""
    if len(task_desc.strip()) < 15:
        return False, "Task description too short — state the goal and acceptance criteria first."
    return True, ""
'''


def l_check_code(typ, lesson):
    """Generate one check function per lesson with constraints."""
    if not lesson["must_contain"] and not lesson["must_not"]:
        return ""
    fn = f"check_{typ}_l{lesson['date'].replace('-', '')}"
    body = ""
    for t in lesson["must_contain"]:
        body += f'    if "{t}" not in task_desc:\n        return False, "教训({lesson["date"]}): {lesson["lesson"][:50]} —— 必须包含「{t}」"\n'
    for t in lesson["must_not"]:
        body += f'    if "{t}" in task_desc:\n        return False, "教训({lesson["date"]}): {lesson["lesson"][:50]} —— 不得包含「{t}」"\n'
    return f'''
def {fn}(task_desc: str) -> tuple[bool, str]:
    """Lesson {lesson['date']}: {lesson['lesson'][:60]}"""
{body}    return True, ""
'''


def main():
    apply = "--apply" in sys.argv
    lessons = parse_lessons()
    print(f"Parsed {len(lessons)} lessons from {LESSONS_DIR}")

    by_type = {}
    for l in lessons:
        by_type.setdefault(l["type"], []).append(l)

    GUARDRAILS_DIR.mkdir(parents=True, exist_ok=True)
    index = {}
    if RULES_INDEX.exists():
        index = json.loads(RULES_INDEX.read_text())

    for typ, items in by_type.items():
        mod = rules_module(typ, items)
        path = GUARDRAILS_DIR / f"{typ}.py"
        print(f"  [{typ}] {len(items)} lessons → {path.name}")
        if apply:
            path.write_text(mod, encoding="utf-8")
            index[typ] = [i["date"] for i in items]
        else:
            print("      (dry-run, use --apply)")

    if apply:
        RULES_INDEX.write_text(json.dumps(index, indent=1, ensure_ascii=False))
        print(f"\nDone. {len(by_type)} guardrail modules generated in {GUARDRAILS_DIR}")
        print("Next: run `python3 guardrail.py <task_type> \"<task description>\"` before tasks.")
    else:
        print("\n[dry-run] Run with --apply to generate guardrail code.")


if __name__ == "__main__":
    main()
